global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'rag-platform'
    service: 'rag-service'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # RAG Platform Service (via host)
  - job_name: 'rag-platform'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    
    # Relabeling for better metric organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+)(?::\d+)?'
        replacement: 'rag-platform'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
