name: Python Tests

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-cache-key.outputs.cache-key }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Generate cache key
      id: set-cache-key
      run: |
        # Create a unique cache key based on test requirements file
        KEY="$RUNNER_OS-pip-$(sha256sum tests/requirements-test.txt 2>/dev/null | sha256sum | cut -d' ' -f1)"
        echo "cache-key=$KEY" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ steps.set-cache-key.outputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        # Only install from tests/requirements-test.txt
        if [ -f "tests/requirements-test.txt" ]; then
          pip install -r tests/requirements-test.txt
        else
          echo "Error: tests/requirements-test.txt not found!"
          exit 1
        fi

  unit-tests:
    name: Unit Tests (3.12)
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Restore cached dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ needs.install-dependencies.outputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install test dependencies (from cache)
      run: |
        python -m pip install --upgrade pip
        # Only install from tests/requirements-test.txt
        if [ -f "tests/requirements-test.txt" ]; then
          pip install -r tests/requirements-test.txt
        else
          echo "Error: tests/requirements-test.txt not found!"
          exit 1
        fi

    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=app --cov-report=xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  integration-tests:
    name: Integration Tests (3.12)
    runs-on: ubuntu-latest
    needs: [install-dependencies, unit-tests]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Restore cached dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ needs.install-dependencies.outputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install test dependencies (from cache)
      run: |
        python -m pip install --upgrade pip
        # Only install from tests/requirements-test.txt
        if [ -f "tests/requirements-test.txt" ]; then
          pip install -r tests/requirements-test.txt
        else
          echo "Error: tests/requirements-test.txt not found!"
          exit 1
        fi

    - name: Run integration tests
      run: |
        pytest tests/integration/ -v